image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - lint

cache:
  paths:
    - node_modules

lint:
  image: node:10-alpine
  stage: lint
  script: "npm ci && npm run lint"
